version: "3.8"
services:
  database:
    container_name: gmdatabase
    image: postgres
    restart: unless-stopped
    env_file:
      - src/WebUI/WebApp/database.env
    ports:
      - "5439:5432"
  api:
    container_name: gmapi
    restart: unless-stopped
    build:
      context: src
      dockerfile: WebUI/WebApp/Dockerfile
    image: govmeeting/api
    ports:
      - 6578:8800
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:8800
    depends_on:
      - database
  web:
    container_name: gmweb
    restart: unless-stopped
    build:
      context: src/WebUI/WebApp/clientapp
    image: govmeeting/web
    ports:
      - "8080:80"
    depends_on:
      - api
