# Based on https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml
name: Dependabot CI
on:
  pull_request:
    branches:
      - main
    # paths:
    #   ["src/WebUI/WebApp/clientapp/**", ".github/workflows/dependabot-ci.yml"]

defaults:
  run:
    working-directory: src/WebUI/WebApp/clientapp

jobs:
  ci:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present

    # - run: npm test
