name: Build frontend 

on:
  push:
    paths: ['frontend/**', '.github/workflows/frontend-build.yaml']
  pull_request:
    paths: ['frontend/**', '.github/workflows/frontend-build.yaml']

defaults:
  run:
    working-directory: frontend/clientapp

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install, unit test and build
        run: |
          npm ci
          npm run build:ci

      - name: run app and cypress tests
        run: |
          npm start &
          npx cypress run
